### ISSUE TITLE
Проверка

### ISSUE THREAD

**Issue by Anton-beep** [Akishy/yacalculator#1]
Тут пусто?

**Comment by Akishy** [comment]
чот залил
ещё после рабочего дня залью, как от работы освобожусь

**Comment by Anton-beep** [comment]
- Весь реализованный ранее функционал работает как раньше, только в контексте конкретного пользователя.
> 10 / 20
> *Кажется, работает ТОЛЬКО добавление выражения, jwt есть*

- У кого выражения хранились в памяти - переводим хранение в SQLite. (теперь наша система обязана переживать перезагрузку)
> 5 / 20
> *sqlite вроде есть, но проверить невозможно*

- У кого общение вычислителя и сервера вычислений было реализовано с помощью HTTP - переводим взаимодействие на GRPC
> 0 / 10

- за покрытие проекта модульными тестами можно получить бонусные 10 баллов
> 10 / 10
> *тесты есть*

- за покрытие проекта интеграционными тестами можно получить бонусные 10 баллов
> 0 / 10
